### ISSUE TITLE
Unable to add new items

### ISSUE THREAD

**Issue by Brian-Graham** [ZeroQI/Absolute-Series-Scanner#124]
I'm unable to add series / episodes sometimes, and I am not entirely sure why. I checked my log dump and here's the error (latest version):

```
Jan 03, 2018 06:08:18.374 [0x7fffacd23340] DEBUG - Adding subdirectory for scanner: /Volumes/Anime/Hunter x Hunter/Specials
Jan 03, 2018 06:08:18.389 [0x7fffacd23340] DEBUG - Skipping over directory 'Hunter x Hunter', as nothing has changed; removing 146 media items from map.
Jan 03, 2018 06:08:18.389 [0x70000e5a8000] DEBUG - HTTP requesting GET http://127.0.0.1:32400/:/metadata/updateProgressMessage?message=Scanning%20Hunter%20x%20Hunter
Jan 03, 2018 06:08:18.390 [0x70000e5a8000] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/:/metadata/updateProgressMessage?message=Scanning%20Hunter%20x%20Hunter
Jan 03, 2018 06:08:18.397 [0x7fffacd23340] ERROR - No module in Absolute Series Scanner
Jan 03, 2018 06:08:18.397 [0x7fffacd23340] ERROR - Error in Python: Looking up module:
Traceback (most recent call last):
  File "/Users/Brian/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 124, in <module>
    set_logging("Root", LOG_FILE_LIBRARY)
  File "/Users/Brian/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 107, in set_logging
    handler = logging.handlers.RotatingFileHandler(os.path.join(LOG_PATH, filename), maxBytes=10*1024*1024, backupCount=backup_count)    #handler = logging.FileHandler(os.path.join(LOG_PATH, filename), mode)
  File "/Applications/Plex Media Server.app/Contents/Resources/Python/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/Applications/Plex Media Server.app/Contents/Resources/Python/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Applications/Plex Media Server.app/Contents/Resources/Python/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Applications/Plex Media Server.app/Contents/Resources/Python/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: (2, 'No such file or directory', '/Users/Brian/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner (custom ASS).log')
```

**Comment by ZeroQI** [comment]
Are you using the beta branch of the scanner?
If not does it happens with it?

**Comment by ZeroQI** [comment]
Create file Plex Media Scanner (custom ASS).log manually, check rights in folder
Use latest beta branch scanner. closing as no reply in 16 days
