### ISSUE TITLE
Bug - anidb4 filelist issue with sub-folders

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#189]
Referencing HAMA #[256](https://github.com/ZeroQI/Hama.bundle/issues/256) at @EndOfLine369's request.

In anidb4 with the following style folder structure:

```
D:/Series/Durarara!!/Durarara!!
D:/Series/Durarara!!/Durarara!! X2
D:/Series/Durarara!!/Durarara!! X2 The Second Arc
D:/Series/Durarara!!/Durarara!! X2 The Third Arc
```
Note - each sub-folder has the relevant [anidb4.id] file inside.

This results in the scanner correctly merging the folders as seasons.  However, the `Durarara!!.filelist `gets overwritten with each sub-folder resulting in the final `.filelist` with only `Durarara!! X2 The Third Arc`

[Durarara Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2521372/Durarara.Logs.zip)

**Comment by EndOfLine369** [comment]
thanks, will fix

**Comment by EndOfLine369** [comment]
Please check now

**Comment by JayXon** [comment]
Crash after your commit
```
Oct 27, 2018 16:42:51.779 [1120] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:\Users\JayXon\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 472, in Scan
    set_logging(foldername=PLEX_LIBRARY[root] if root in PLEX_LIBRARY else '', filename=log_filename+'.filelist.log', mode='w') #add grouping folders filelist
  File "C:\Users\JayXon\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 219, in set_logging
    if os.sep=="\\":  LOG_FILE = winapi_path(LOG_FILE) # Bypass DOS path MAX_PATH limitation
  File "C:\Users\JayXon\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 201, in winapi_path
    if path.startswith(u"\\\\"):  return u"\\\\?\\UNC\\" + path[2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 109: ordinal not in range(128)
Oct 27, 2018 16:42:51.779 [1120] ERROR - We got an error scanning in D:\Anime
```

**Comment by EndOfLine369** [comment]
Merged, thanks for the fix

**Comment by sven-7** [comment]
Tested -- good to go.
