### ISSUE TITLE
"has show empty, report logs to dev ASAP"

### ISSUE THREAD

**Issue by 2600box** [ZeroQI/Absolute-Series-Scanner#228]
Scanner is otherwise up to date and working as expected except for this one which has the following in logs. Have tried fresh library and it never appears.

File is a single mkv with no directory.

```
Library: 'no valid X-Plex-Token.id', root: '/plex_copies/Anime', path: '', files: '1', dirs: '7'
Plex scan start: 2019-08-31 01:52:33,758813
=============================================================================================================================================================
[All files were seen as unknown(5XX). Trying one more time without miscellaneous string filtering.]
show: '', s00e502-502, file: '/plex_copies/Anime/Little_Witch_Academia_The_Enchanted_Parade.mkv' has show empty, report logs to dev ASAP
"" s00e502                         "__" "Little Witch Academia The Enchanted Parade" "Little_Witch_Academia_The_Enchanted_Parade.mkv"
root level manual call to Grouping folders
```

There is a scanner error, but it does not relate to this file and appears to continue without a problem after the error. FWIW:

```
Aug 31, 2019 01:41:52.644 [0x7f362aef9700] INFO - Plex Media Scanner v1.16.5.1554-1e5ff713d - Ubuntu PC x86_64 - build: linux-x86_64 - GMT 00:00
Aug 31, 2019 01:41:52.644 [0x7f362aef9700] INFO - Linux version: 18.04.3 LTS (Bionic Beaver), language: C
Aug 31, 2019 01:41:52.644 [0x7f362aef9700] INFO - Processor Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Aug 31, 2019 01:41:52.644 [0x7f362aef9700] INFO - /usr/lib/plexmediaserver/Plex Media Scanner --scan --refresh --section 6
Aug 31, 2019 01:51:41.300 [0x7f3632e09280] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Scanners.bundle/Contents/Resources/Common/VideoFiles.py", line 196, in Scan
    Filter.Scan(path, files, mediaList, subdirs, video_exts, root)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Scanners.bundle/Contents/Resources/Common/Filter.py", line 109, in Scan
    ignore_list = glob.glob(pattern)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/fnmatch.py", line 56, in filter
    _cache[pat] = re_pat = re.compile(res)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range
Aug 31, 2019 01:51:41.300 [0x7f3632e09280] ERROR - Error scanning directory [Komorebi] Violet Evergarden [BD 1080p x264-10bit FLAC]/Creditless OP+ED.
Aug 31, 2019 01:52:21.719 [0x7f3632e09280] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Scanners.bundle/Contents/Resources/Common/VideoFiles.py", line 196, in Scan
    Filter.Scan(path, files, mediaList, subdirs, video_exts, root)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Scanners.bundle/Contents/Resources/Common/Filter.py", line 109, in Scan
    ignore_list = glob.glob(pattern)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/fnmatch.py", line 56, in filter
    _cache[pat] = re_pat = re.compile(res)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range
Aug 31, 2019 01:52:21.719 [0x7f3632e09280] ERROR - Error scanning directory [-__-'] Planetes [BD 1080p AAC]/Pics.
Aug 31, 2019 01:52:22.459 [0x7f3632e09280] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Scanners.bundle/Contents/Resources/Common/VideoFiles.py", line 196, in Scan
    Filter.Scan(path, files, mediaList, subdirs, video_exts, root)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Scanners.bundle/Contents/Resources/Common/Filter.py", line 109, in Scan
    ignore_list = glob.glob(pattern)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/fnmatch.py", line 56, in filter
    _cache[pat] = re_pat = re.compile(res)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range
Aug 31, 2019 01:52:22.460 [0x7f3632e09280] ERROR - Error scanning directory [-__-'] Planetes [BD 1080p AAC]/Scans.
```

**Comment by ZeroQI** [comment]
The scanner cannot determine for "/Little_Witch_Academia_The_Enchanted_Parade.mkv" the series name, season name, episode name, and am not sure what the scanner should do or if i should fix at the naming is atrocious. Should at least have been named "Little Witch Academia The Enchanted Parade/Little_Witch_Academia_The_Enchanted_Parade.mkv" to flag it as a movie

your folder name causing issues is  "[-__-'] Planetes [BD 1080p AAC]"
- Try to remove the single apostrophe.
- Error reported is not in my code but Plex one so cannot fix. Not even sure ASS is running from the output.
