### ISSUE TITLE
Scanner Stalling

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#33]
Two (related) issues that have popped up.  I experienced this some while testing for HAMA [#48](https://github.com/ZeroQI/Hama.bundle/pull/48)

- **Issue 1**: The Scanner seems to stall at times for me.  The first series it scans is ".hack SIGN" -- which I renamed to "hack SIGN" and labeled the episodes as "abs# - title.ext".  I have tvdb2 going for this file.

```
2016-06-06 23:00:07 === Library "Anime Series", Root: "A:\Anime Series",  Launched: '2016-06-06 23:00:07'========================================================================
2016-06-06 23:00:07 keep_zero_size_files: 'False'
2016-06-06 23:00:07 no_timestamp:         'False'
2016-06-06 23:00:07 season_from_folder:   'False'
2016-06-06 23:00:07 =============================================================================================================================================================
2016-06-06 23:00:07 Scanner call - root: 'A:\Anime Series', path: '', dirs: '261', files: '0'
2016-06-06 23:00:07 =============================================================================================================================================================
2016-06-06 23:00:08 Scanner call - root: 'A:\Anime Series', path: 'hack SIGN', dirs: '0', files: '65'
2016-06-06 23:00:08 =============================================================================================================================================================
2016-06-06 23:00:08 file: 'A:\Anime Series\hack SIGN\tvdb2.id', ext: 'id' not in video_ext
2016-06-06 23:00:08 folder_show: 'hack SIGN [tvdb2-79099]', tvdb id: '79099'
2016-06-06 23:00:08 TVDB season mode (2) enabled, serie url: 'https://thetvdb.com/api/A27AD9BE0DA63333/series/79099/all/en.xml'
```

That was where it sat from 23:00 to 8:00 the next day before being cancelled. I ran it again just now with clean logs -- here is everything that generated.

[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/302592/Logs.zip)

I pulled the series from my library and the scanner ran -- here are those logs:

[post hack sign logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/302611/post.hack.sign.logs.zip)

---------------

- **Issue 2**:  This could be a mapping issue with ScudLee, but for "Voltron - Defender of the Universe" there seem to be two TVDB series associated with it.  One is 78646 - Voltron: Defender of the Universe and the second is 147921 - Beast King GoLion.  Long story short, it's the same show, but when it became Voltron in the US it was changed a little bit and there are different episodes.  That's why there are two series.  The odd part about the scanner here is that even though I have a TVDB2.id (78646) file in Voltron, it still maps to the latter show.

Following Issue 1 test, I changed the name of the Voltron folder from "Voltron - Defender of the Universe" to "Voltron" to initiate a scan, but the scanner also stalled.  Here are the logs for that.

[voltron logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/302678/voltron.logs.zip)

**Comment by ZeroQI** [comment]
Some right issues ?
Failed to delete session directory (boost::filesystem::status: Access is denied: "C:\Users\Sven\AppData\Local\Plex Media Server\Cache\Transcode\Sessions\plex-transcode-E340924D-1D11-4270-8E5B-7140DB8B83B0-ab0ec757-8bc4-402e-b72a-3f2a542d86ee\media-00003.ts")

No crash in Plex Media Scanner.log... Not sure but it may be specific to your plex session...
Seem it froze after:
2016-06-07 08:53:25 TVDB season mode (2) enabled, serie url: 'https://thetvdb.com/api/A27AD9BE0DA63333/series/79099/all/en.xml'

but should give an error, not freeze...

**Comment by sven-7** [comment]
What's odd is that as soon as I removed the series from the library and re-scanned, it was fine.  That's what leads me to believe it's something else.  

Here is one scanning issue I found.  It's probably caused by my numbering them absolutely, whereas before I had it in season format.  I updated TVDB (ReBoot was missing absolute numbering) and the metadata hasn't come downstream yet, but still wanted to pass this along.

```

Jun 07, 2016 18:03:41:806 [3660] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:\Users\Sven\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 318, in Scan
    except Exception as e:  Log("xml loading issue"); Log(e)
  File "C:\Users\Sven\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 104, in Log
    file.write(("" if no_timestamp else time.strftime("%Y-%m-%d %H:%M:%S") + " ") + entry + "\n")
TypeError: cannot concatenate 'str' and 'URLError' objects
Jun 07, 2016 18:03:41:806 [3660] ERROR - We got an error scanning in B:\Anime Series\ReBoot
Jun 07, 2016 18:03:41:808 [3660] ERROR - There were errors scanning location: B:\Anime Series
Jun 07, 2016 18:03:41:808 [3660] DEBUG - Since it was an incomplete scan, we are not going to whack missing media.
Jun 07, 2016 18:03:41:808 [3660] DEBUG - Refreshing metadata for 'ReBoot' (agent: com.plexapp.agents.hama)
Jun 07, 2016 18:03:41:808 [3660] DEBUG - Refreshing GUID: 'com.plexapp.agents.hama://tvdb3-73025?lang=en'
Jun 07, 2016 18:03:41:809 [3660] DEBUG - HTTP requesting GET http://127.0.0.1:32400/system/agents/update?mediaType=2&force=1&guid=com%2Eplexapp%2Eagents%2Ehama%3A%2F%2Ftvdb3-73025%3Flang%3Den&id=48061
Jun 07, 2016 18:03:41:809 [2680] DEBUG - HTTP requesting GET http://127.0.0.1:32400/:/metadata/notify/changeItemState?librarySectionID=2&metadataItemID=48061&metadataType=2&state=3&metadataState=queued

```

**Comment by sven-7** [comment]
Ultimately @ZeroQI, I think you're right.  This is probably Windows or Plex that's messing with the scanner.  I also had trouble loading the XML files via browser, so it could have been a TVDB issue at some point as well.  I was able to get both back in, though I had to do it one at a time.  When I added .hack and Voltron, it kicked the bucked on the latter.  Not sure what to make of it, but will close this out unless someone else thinks more investigating is needed.

**Comment by sven-7** [comment]
Closed #33.

**Comment by sven-7** [comment]
Thanks!! 😄

**Comment by ZeroQI** [comment]
Brilliant
