### ISSUE TITLE
TypeError: decode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by maddin77** [ZeroQI/Absolute-Series-Scanner#345]
Operating system and version: NVIDIA Shield Android TV Version 8.2.2
Plex version: 1.22.1.4275

----

```
Apr 03, 2021 19:09:35.757 [8184] DEBUG - Scanner: Processing directory /storage/SYNOLOGY_NAS/plex_media/media/DE/Anime/Serien/Cowboy.Bebop.S01.German.DTS.5.1.DL.1080p.BluRay.x264-AST4u (parent: yes)
Apr 03, 2021 19:09:35.770 [8184] DEBUG - Directory had 26 files, database had 0 files, can't skip.
Apr 03, 2021 19:09:35.771 [8184] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 492, in Scan
    files        = [sanitize_path(p) for p in files] #unicode
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 474, in sanitize_path
    return p.decode(sys.getfilesystemencoding())
TypeError: decode() argument 1 must be string, not None
Apr 03, 2021 19:09:35.771 [8184] DEBUG - HTTP requesting PUT http://127.0.0.1:32400/activities/01f5769d-8e9f-491d-87b7-3620fa221078?percentComplete=%2B16%2E5&subtitle=Cowboy%2EBebop%2ES01%2EGerman%2EDTS%2E5%2E1%2EDL%2E1080p%2EBluRay%2Ex264-AST4u
Apr 03, 2021 19:09:35.774 [8184] DEBUG - HTTP 200 response from PUT http://127.0.0.1:32400/activities/01f5769d-8e9f-491d-87b7-3620fa221078?percentComplete=%2B16%2E5&subtitle=Cowboy%2EBebop%2ES01%2EGerman%2EDTS%2E5%2E1%2EDL%2E1080p%2EBluRay%2Ex264-AST4u
Apr 03, 2021 19:09:35.774 [8184] ERROR - We got an error scanning in /storage/SYNOLOGY_NAS/plex_media/media/DE/Anime/Serien
```

It seems that `sys.getfilesystemencoding()` returns `None` on my system. When i replace all the calls with just `'utf-8'` it works fine.

**Comment by ZeroQI** [comment]
The following should resolve then, but it's not normal it returns None...
`return p.decode(sys.getfilesystemencoding() or 'utf-8')`
Can you give the line numbers will all the call you changed and will push to master

**Comment by maddin77** [comment]
394, 431 & 474.
