### ISSUE TITLE
Scanner Crash - IndexError: list index out of range

### ISSUE THREAD

**Issue by thecoolreaver** [ZeroQI/Absolute-Series-Scanner#367]
## Platform

Operating system and version: Ubuntu 20.04 LTS
Plex version: 1.23.6.4881

## Expected Behavior

Scanner should scan the folders and files and find whats changed?

## Current Behavior

Scanner crashes with a IndexError?
```
Aug 02, 2021 17:58:16.907 [0x7f62a8955848] DEBUG - Scanning YouTube: Channels (Playlists) using en(Absolute Series Scanner) with 6161 current media items and 1 section locati
ons in the database.
Aug 02, 2021 17:58:17.321 [0x7f62a8955848] DEBUG - Performing a scan with 'Absolute Series Scanner' (language: en virtual: 0).
Aug 02, 2021 17:58:17.321 [0x7f62a8955848] DEBUG -   * Scanning /data/YouTube/Channels
Aug 02, 2021 17:58:17.321 [0x7f62a8955848] DEBUG - Scanner: Processing directory /data/YouTube/Channels (parent: no)
Aug 02, 2021 17:58:17.327 [0x7f62a8955848] DEBUG - File '/data/YouTube/Channels/Because Science [UCvG04Y09q0HExnIjdgaqcDQ]/Because DC Science [PLWTxVg44uPplr-TRGo7JrfDVNbFOUt
IDz]/Aquaman Under Pressure _ Because Science Live [pG_mfGHURtI].mkv' didn't exist, can't skip.
Aug 02, 2021 17:58:45.439 [0x7f62a8955848] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 1186, in Scan
    Scan(path, sorted(subdir_files), media, sorted(subdir_dirs), language=language, root=root, kwargs_trigger=True)  #relative path for dir or it will show only grouping fold
er series
  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 900, in Scan
    reverse      = False if source=='youtube3' else Dict(json_full[0], "snippet", "publishedAt") > Dict(json_full[-1], "snippet", "publishedAt")  #Dict(video, 'contentDetails
', 'videoPublishedAt')
IndexError: list index out of range
Aug 02, 2021 17:58:45.440 [0x7f62a8955848] ERROR - We got an error scanning in /data/YouTube/Channels
```

## Steps to Reproduce

Unknown

## Additional information

I did think it was a API error, but i double checked my API is used in the python file and in Plex and with all relating files just in case, no change.

**Comment by ZeroQI** [comment]
Path: 'Because Science [UCvG04Y09q0HExnIjdgaqcDQ]/Because DC Science [PLWTxVg44uPplr-TRGo7JrfDVNbFOUt
IDz]/Aquaman Under Pressure _ Because Science Live [pG_mfGHURtI].mkv
Possible faulty index: 
- json_full[0]
- json_full[-1]

json_full seem to have no index present, changing code to the following would fix (would cache results so Plex dance necessary unless folder content changed since last scan)
`Dict(json_full, 0, "snippet", "publishedAt") > Dict(json_full, -1, "snippet", "publishedAt")  #Dict(video, 'contentDetails', 'videoPublishedAt')`

**Comment by thecoolreaver** [comment]
That did fix it!
